---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":arrow_up: upgrade:"
    ignore:
      - dependency-name: "react"
        versions: [">=18.3.1"]
      - dependency-name: "react-dom"
        versions: [">=18.3.1"]
      - dependency-name: "react-router"
        versions: [">=6.26.0"]
      - dependency-name: "react-router-dom"
        versions: [">=6.26.0"]
      - dependency-name: "vite"
        versions: [">=5.4.18"]
